I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 140, in script
    u curious"Да.. Понял... Сделаю, да"
Exception: Say has image attributes ('curious',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 140, in script
    u curious"Да.. Понял... Сделаю, да"
  File "C:\Users\tihan\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\tihan\Desktop\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\Users\tihan\Desktop\renpy-8.0.3-sdk\renpy\character.py", line 1206, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\tihan\Desktop\renpy-8.0.3-sdk\renpy\character.py", line 1030, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\tihan\Desktop\renpy-8.0.3-sdk\renpy\character.py", line 956, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('curious',), but there's no image tag associated with the speaking character.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Game 1.0
Sun Dec 11 14:22:13 2022
